---
deployment:
  tasks:
    - export DEPLOYPATH=/home/willia14/public_html/
    - /bin/cp -R img $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp .htaccess $DEPLOYPATH
    - /bin/cp favicon.ico $DEPLOYPATH
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp contact.html $DEPLOYPATH
    - /bin/cp projects.html $DEPLOYPATH
    - /bin/cp services.html $DEPLOYPATH
    - /bin/cp privacypolicy.html $DEPLOYPATH
    - /bin/cp thanks.html $DEPLOYPATH
    - /bin/cp script.js $DEPLOYPATH
